### PR TITLE
Track gitignore files via .gitmodule as opposed to copy+paste

### PR DESCRIPTION
**Pull request by munrocape**
Implemented this after reading a comment on the [PH post](http://www.producthunt.com/posts/joe-gitignore-magician) for this. Thought it would be an interesting thing to read up on. 

[.gitmodules](http://git-scm.com/docs/gitmodules) allow to nest .git repos.

### CODE REVIEW

**Comment by munrocape** [comment]
Looks like I was inched out by @csu :cold_sweat:

**Comment by csu** [comment]
@munrocape Haha. Exactly the same commits too :stuck_out_tongue:

**Comment by munrocape** [comment]
@csu I was fiddling around with the mac GUI. Turned my back on the command line - now I've learned my lesson! :stuck_out_tongue_closed_eyes: 

I ended up just doing this. Surprisingly powerful (as it often can be)

``` shell
> rm -rf joe/data
> git submodule add https://github.com/github/gitignore.git joe/data
```

**Comment by karan** [comment]
You guys are awesome.

**Pull request closed without merging**
